### ISSUE TITLE
申请添加我的模板加进库里

### ISSUE THREAD

**Issue by sikouhjw** [brenner8023/gdut-course#11]
申请将 https://github.com/sikouhjw/gdutthesis 添加到[毕业设计#毕业论文latex模板](https://github.com/brenner8023/gdut-course/tree/master/public/%E6%AF%95%E4%B8%9A%E8%AE%BE%E8%AE%A1#%E6%AF%95%E4%B8%9A%E8%AE%BA%E6%96%87latex%E6%A8%A1%E6%9D%BF)里。

目前算是半个官方模板 https://github.com/sikouhjw/gdutthesis/issues/2#issuecomment-970057767

**Comment by brenner8023** [comment]
已添加
